pull_request_rules:
  - name: automatic merge for master when CI passes and 1 review and not WIP
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - base=master
      - label!=work-in-progress
    actions:
      merge:
        method: merge
